name: build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fmt
      run : cargo fmt --all -- --check
    - name: clippy
      run : cargo clippy --all --all-targets -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
